AppHome/urls.py
from django.urls import path,include,re_path
from .views import home,project,allProjects ,addComment , addDonate ,addRate , reportPro , reportCom
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('', home),  
    re_path(r'^project/(?P<pro_id>\d+)/$', project),
    re_path(r'^project/addDonate/(?P<pro_id>\d+)/$', addDonate),
    re_path(r'^project/(?P<pro_id>\d+)/(?P<msg>\w+)/$', project),  
    re_path(r'^project/addRate/(?P<pro_id>\d+)/(?P<msgR>\w+)/$', addRate),  
    path('allProject', allProjects), 
    re_path(r'^allProject/$', allProjects),   
    re_path(r'^project/addComment/(?P<pro_id>\d+)/$', addComment), 
    re_path(r'^project/reportPro/(?P<pro_id>\d+)/$', reportPro),   
    re_path(r'^project/reportCom/(?P<c_id>\d+)/$', reportCom),   
]

AppProject/urls.py
from django.urls import path,include
from .views import createProject, create_tags

app_name="AppProject"

urlpatterns = [
    path('create/', createProject, name='create'),
    path("create_tag/", create_tags, name='create_tag')
]

Project/urls.py
from django.contrib import admin
from django.urls import path,include
from AppHome.views import home
from django.conf.urls.static import static
from django.conf import settings
#from AppCategory import urls 
#from AppHome import urls 
#from AppProject import urls 
#from AppTags import urls 
#from AppUsers import urls 

urlpatterns = [
    path('user/', include('django.contrib.auth.urls')),
    path('users/', include('AppUsers.urls')),
    path('admin/', admin.site.urls),
    path('tag/', include('AppTags.urls') ),
    path('project/', include('AppProject.urls')),
    path('home/',include('AppHome.urls')),
    path('category/', include('AppCategory.urls')),
    path('AppProfile/', include('AppProfile.urls')),
    path('accounts/profile/',home),
    path('accounts/', include('django.contrib.auth.urls')),
    path('appadmin/', include('appadmin.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appadmin/urls.py
from django.urls import path,include
from .views import adminpage,createCat,createOptionInfo,delete_Cat,delete_OptionInfo,select_five,reportPro
app_name="appadmin"
urlpatterns = [
    path('', adminpage ,name="home"),
    path('createCat/', createCat ,name="createCat"),
    path('createOptionInfo/', createOptionInfo ,name="createOptionInfo"),
    path('delete_Cat/<int:Cat_ID>', delete_Cat ,name="delete_Cat"),
    path('delete_OptionInfo/<int:Opt_ID>', delete_OptionInfo ,name="delete_OptionInfo"),
    path('select_five/<int:pid>', select_five ,name="select_five"),
    path('reportPro/<int:pro_id>', reportPro ,name="reportPro"),
   
]

templates/allProjects.html
{% extends "base.html"%} {% load static%}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %} Home {% endblock %}</title>

    {% block style %}
    <style type="text/css">
      .card-horizontal {
        display: flex;
        flex: 1 1 auto;
      }
    </style>
    <link rel="stylesheet" href="{%static 'assets/css/style.css'%}" />
    {% endblock %}
  </head>

  <body>
    {% block searchForm %}

    <form class="form-inline my-2 my-lg-0" action='../../../home/allProject'>
      <input
        id="tags"
        class="form-control mr-sm-2 btnChanged"
        type="search"
        placeholder="Search"
        name="searching"
      />
      <button
        class="btn btn-outline-danger my-2 my-sm-0"
        type="submit"
       
      >
        Search
      </button>
    </form>

    <script>
      $( function() {

              var availableName = [
                  {% for item in allProject %}
                      "{{item.title}}",
                  {% endfor %}
              ];

              var availableTags = [
                  {% for item2 in allTag %}
                      "{{item2.tagName}}",
                  {% endfor %}
              ];

              var searchingItem= availableName.concat(availableTags);


              $( "#tags" ).autocomplete({
                source: searchingItem
              });
            } );

      {% comment %} function sendStringToSearch()
      {
        var stringTosearch = document.getElementById("tags").value
        console.log( stringTosearch)
        if(stringTosearch != '')
        {
         
          window.open("../../../home/allProject/"+stringTosearch );

          //var x = "../../../home/allProject/"
          
          //window.location.href= x.concat(stringTosearch);
        }
                     
      } {% endcomment %}
    </script>
    {% endblock %} {% block content %}

    
    <div class="container" style="border: px solid">
      <div class="row m-5">
        {% for item in allProject %}
        <div class="col-md-7 mt-5 h-100" onclick="detail({{item.id}})">
          <div class="card">
            <div
              class="card-horizontal bg-light w-100"
              style="border: px solid yellow"
            >
              <div class="img-square-wrapper w-50" style="border: px solid red">
                <img
                  class="card-img-top w-100 rounded float-left"
                  src="/media/{{item.img}}"   width="200" height="300"
                  alt=""
                />
              </div>
              <div class="card-body w-50 p-0 m-0" style="position: relative">
                <h4 class="card-title ml-3 mt-3" style="color: #fb6355">
                  {{item.title}}
                </h4>
                <p class="card-text ml-3">{{item.details}}</p>

                <div
                  class="bg-dark w-100"
                  style="position: absolute; bottom: 0%; right: 0%"
                >
                  <div
                    class="card-deck p-0 m-0 border-0"
                    style="
                      height: 10px;
                      width: 100%;
                      background-color: #fb63552c;
                    "
                  >
                    <div
                      class="presentageProgress progress-bar"
                      role="progressbar"
                      style="width: 50%; background-color: #fb6355"
                      style="background: #fb6355"
                      aria-valuenow="25"
                      aria-valuemin="0"
                      aria-valuemax="100"
                    ></div>
                  </div>
                  <div class="row">
                    <div class="col-4 text-center border-right border-light">
                      <p class="font-weight-bold text-light">Current</p>
                      <p class="text-light">{{item.actualDonation}} EGP</p>
                    </div>

                    <p
                      class="actual col-4 h4 text-center align-middle font-weight-bold text-light"
                      style="font: 20px"
                    ></p>

                    <div class="col-4 text-center border-left border-light">
                      <p class="font-weight-bold text-light">Target</p>
                      <p class="text-light">{{item.totalTarget}} EGP</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <script>
              x={{ forloop.counter0 }}
              console.log(typeof(x))
              total={{item.totalTarget}}
              actual={{item.actualDonation}}
              presentage=(actual/total)*100;
              document.getElementsByClassName("actual")[x].innerText=Math.round(presentage)+"%"
              document.getElementsByClassName("presentageProgress")[x].style.width=presentage+"%"

              function detail(ele)
              {
                window.location.href="../home/project/"+ele+"";
              }
            </script>
          </div>
        </div>
        <div class="col-md-1"></div>
        {% endfor %}
      </div>
      <div class=""></div>
    </div>
    {% endblock %}
  </body>
</html>

templates/base.html
{% load static%}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width ,initial-scale=1">
    <title>{% block title %} Base html {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
  <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="jQuery-plugin-progressbar.js"></script>
   <script src=  
"https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.js">  
    </script>  
    
    <script src=  
"https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js">  
    </script>  
    
    <link href=  
"http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/ui-lightness/jquery-ui.css"
        rel="stylesheet" type="text/css" />  
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <!-- -->

    <!-- -->
    <style>
        body {
            padding: 0px;
            margin: 0px;
            position: relative;
        }

        #colorNav {
            font-family: "Raleway", Helvetica, sans-serif;
            font-size: 15px;
            font-weight: 600;

            background-color: white;
           
            z-index: 10;
        }

  

        .colorWhite {
            font-size: 18;
            color: rgb(59, 57, 57);
            color: rgb(77, 0, 107);
        }

        .fontLogo {
         
          font-family: 'Ubuntu', arial, sans-serif;
          font-weight: 700;
          font-size:30px;
          font-style: italic;
          
        }
        .activeBTN {
            background-color: #fb6355;
            color:white
        }
.btnChanged:focus {
    border-color: #000000;
    box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.075) inset, 0px 0px 8px rgba(0, 0, 0, 0.5);
}
    </style>
     {% block style %} {% endblock %}
</head>

<body class=" " data-spy="scroll" data-offset="0" data-target="#myScrollspy" style="background-image: url('{%static 'assets/images/bg-body.jpg' %}')">
 <div id="preloader">
      <div class="jumper">
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>

    <!-- nav bar when big screen-->
    <!-- <img id="coverImg" > -->
    {% comment %} <nav id="colorNav" class=" p-0   navbar d-none  d-md-block  d-lg-block bg-light d-xl-block shadow  bg-white rounded ">
        <a href="#" class="logo">
                <img src="{%static 'assets/images/logo.png'%}" />
              </a>
        <div class=" w-75  m-auto  text-center">
            <a href="#" class="p-3 colorWhite w3-hover-black btn btnChanged rounded-0 activeBTN" data-target="#myCarousel" data-slide-to="0">Home</a>
            <a href="#" class="p-3 colorWhite w3-hover-black btn btnChanged rounded-0" data-target="#myCarousel" data-slide-to="1">About</a>
            <a href="#" class="p-3 colorWhite w3-hover-black btn btnChanged rounded-0" data-target="#myCarousel" data-slide-to="2">Resume</a>
            <a href="#" class="p-3 colorWhite w3-hover-black btn  rounded-0" data-toggle="modal" data-target="#myModal">Contact</a>
        </div>
    </nav>
    <script>

        var header = document.getElementById("colorNav");
        var btns = header.getElementsByClassName("btnChanged");
        for (var i = 0; i < btns.length; i++) {
            btns[i].addEventListener("click", function () {

                var current = document.getElementsByClassName("activeBTN");
                current[0].className = current[0].className.replace(" activeBTN", "");
                this.className += " activeBTN";
            });
        }

    </script>
  
    <!-- nav bar when small screen-->
    <nav id="colorNav" class=" p-2 m-0 navbar d-block navbar-expand-xs navbar-expand-md  d-md-none  d-lg-none  d-xl-none  bg-light navbar-light   ">
        <a href="#contact" class="myName p-3 colorWhite   rounded-0">Walaa</a>
        <button class=" navbar-toggler float-right " type="button" data-target="#navLinks" data-toggle="collapse">
            <span class=" navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse   clearfix" id="navLinks">
            <ul class="nav flex-column" class="">
                <a href="#homePage" class="p-3 colorWhite w3-hover-black  btn border m-1 rounded-2 active" data-target="#myCarousel" data-slide-to="0">Home</a>
                <a href="#" class="p-3 colorWhite w3-hover-black btn border m-1 rounded-2 " data-target="#myCarousel" data-slide-to="1">About</a>
                <a href="#" class="p-3 colorWhite w3-hover-black btn border m-1 rounded-2" data-target="#myCarousel" data-slide-to="2">Resume</a>

                <a href="#" class="p-3 colorWhite w3-hover-black btn border m-1 rounded-2" data-toggle="modal" data-target="#myModal">Contact</a>
            </ul>
        </div>
    </nav> {% endcomment %}

<nav class="navbar navbar-expand-lg navbar-light bg-light " id="colorNav">
  <a class="navbar-brand fontLogo ml-5 mr-5" href="#" style="color: #fb6355">Hope</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse " id="navbarSupportedContent" >
    <ul class="navbar-nav mr-auto"  >
      <li class="nav-item ">
        <a class="nav-link colorWhite w3-hover-red btn btnChanged rounded-0 activeBTN" href="../../home">Home </a>
      </li>

        {% if all == 'all' %}
       <li class="nav-item dropdown"  >
        <a class="nav-link dropdown-toggle colorWhite w3-hover-red btn btnChanged rounded-0"   id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
          Top Projects
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown" > 
       
          <a class="dropdown-item" href="#Featured">Featured Project</a>
          <a class="dropdown-item" href="#Recommended">Recommended Project</a>
          <a class="dropdown-item" href="#Last">Last Project</a>
        </div>
      </li>
      {% endif %}
      <li class="nav-item ">
        <a class="nav-link colorWhite w3-hover-red btn btnChanged rounded-0 " href="../../home/allProject">all Projects </a>
      </li>
       <li class="nav-item ">
        <a class="nav-link colorWhite w3-hover-red btn btnChanged rounded-0 " href="../../../project/create">create Project</a>
      </li>
       <li class="nav-item ">
        <a class="nav-link colorWhite w3-hover-red btn btnChanged rounded-0 " href="../../AppProfile">Profile </a>
      </li>
     
      
    </ul>
    
     {% block searchForm %} {% endblock %}
    
   
   
      <ul class="navbar-nav  ml-5"  >
        <li class="nav-item" >
          <a class="nav-link w3-hover-red btn" href="../../users/logout">
           {% if user.is_authenticated %}
           Logout
            {% else %}
            Login
            {% endif %}
           </a>
        </li>
      </ul>
   
  </div>
</nav>
   <script>

        var header = document.getElementById("colorNav");
        var btns = header.getElementsByClassName("btnChanged");
        for (var i = 0; i < btns.length; i++) {
            btns[i].addEventListener("click", function () {

                var current = document.getElementsByClassName("activeBTN");
                current[0].className = current[0].className.replace(" activeBTN", "");
                this.className += " activeBTN";
            });
        }

    </script>
     {% block content %}  {% endblock %}

     <footer class="text-light" style="background-color: black;">
         <div class="row my-2 justify-content-center ">
             <div class="col-11">
                 <div class="row ">
                     <div class="col-xl-8 col-md-4 col-sm-4 col-12 my-auto mx-auto a">
                         <h3 class="text-muted mb-md-0 mb-5 bold-text">Pepper.</h3>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-12">
                         <h6 class="mb-3 mb-lg-4 bold-text text-muted"><b>MENU</b></h6>
                         <ul class="list-unstyled">
                             <li>Home</li>
                             <li>About</li>
                             <li>Blog</li>
                             <li>Portfolio</li>
                         </ul>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-12">
                         <h6 class="mb-3 mb-lg-4 text-muted bold-text mt-sm-0 mt-5"><b>ADDRESS</b></h6>
                         <p class="mb-1 text-light">605, RATAN ICON BUILDING</p>
                         <p class="text-light">SEAWOODS SECTOR</p>
                     </div>
                 </div>
                 <div class="row ">
                     <div class="col-xl-8 col-md-4 col-sm-4 col-auto my-md-0 mt-5 order-sm-1 order-3 align-self-end">
                         <p class="social text-muted mb-0 pb-0 bold-text"> <span class="mx-2"><i class="fa fa-facebook" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-linkedin-square" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-twitter" aria-hidden="true"></i></span> <span class="mx-2"><i class="fa fa-instagram" aria-hidden="true"></i></span> </p><small class="rights"><span>&#174;</span> Pepper All Rights Reserved.</small>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-1 align-self-end ">
                         <h6 class="mt-55 mt-2 text-muted bold-text"><b>ANIRUDH SINGLA</b></h6><small> <span><i class="fa fa-envelope" aria-hidden="true"></i></span> anirudh@gmail.com</small>
                     </div>
                     <div class="col-xl-2 col-md-4 col-sm-4 col-auto order-2 align-self-end mt-3 ">
                         <h6 class="text-muted bold-text"><b>RISHABH SHEKHAR</b></h6><small><span><i class="fa fa-envelope" aria-hidden="true"></i></span> rishab@gmail.com</small>
                     </div>
                 </div>
             </div>
         </div>
     </footer>


       

    {% block javascript %} 
    
    
    {% endblock %}
</body>

</html>

templates/create_project.html
{% extends "base.html" %}

<!-- <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Project</button>
</form> -->

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<form class="form-horizontal" action="{% url 'AppProject:create_tag' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label class="control-label col-sm-2" for="tag">Add Tag:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="tag" placeholder="Enter Tag" name="tag">
            <br>
            <input type="submit" class="btn btn-primary" value="Add Tag">
        </div>
    </div>
</form>
<form class="form-horizontal" action="{% url 'AppProject:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label class="control-label col-sm-2" for="title">Title:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="title" placeholder="Enter title" name="title">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="details">Details:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="details" placeholder="Enter details" name="details">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="category">Category:</label>
        <div class="col-sm-10">
            <select id="category" class="form-select form-control" aria-label="Default select example" name="category">
                {% for category in categories %}
                <option value="{{ category.id }}">{{category.categoryName}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="details">Total Target:</label>
        <div class="col-sm-10">
            <input type="number" class="form-control" id="total-target" placeholder="Enter Total Target"
                name="totalTarget">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="start-time">Start Time:</label>
        <div class="col-sm-10">
            <input type="datetime-local" class="form-control" id="start-time" name="startTime">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="end-time">End Time:</label>
        <div class="col-sm-10">
            <input type="datetime-local" class="form-control" id="end-time" name="endTime">
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="end-time">Enter Images:</label>
        <div class="col-sm-10">
            <input type="file" id="files" name="files" multiple>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="tag">Tag:</label>
        <div class="col-sm-10">
            <select id="tag" class="form-select form-control" aria-label="Default select example" name="tag" multiple>
                {% for tag in tags %}
                <option value="{{ tag.id }}">{{tag.tagName}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="form-group mx-3">
        <div class="col-sm-10"></div>
            <input type="submit" class="btn btn-primary" value="Create Project">
        </div>
    </div>
    
</form>
{% endblock %}

templates/deleteUser.html
{% extends "base.html"%} {% load static%}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %} Delete User {% endblock %}</title>
    {% block style %} {% endblock %}
  </head>

  <body>
    {% block content %}

    <div class="container-fluid">
      <div class="col-8 m-5 bg-light p-5">
        Are you sure delete your account ?!
        <form class="mt-3" method="POST">
          {% csrf_token %}
          <div class="col">
            <label for="passIn">Password</label>
            <input
              id="passIn"
              type="password"
              class="form-control"
              placeholder="Pass"
              name="password"
              required
            />
            <div class="invalid-feedback">Please Enter Password</div>
          </div>

          <input type="submit" class="mt-5" value="Delete" />
          <input
            type="button"
            class="mt-5"
            onclick="location.href='../'"
            value="Cancel"
          />
        </form>
        <p>{{msg}}</p>
      </div>
    </div>

    {% endblock %}
  </body>
</html>

templates/ِadminpage.html
{% extends "base.html" %}

<!-- <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Project</button>
</form> -->

{% block content %}
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<hr>
<h1>Create Category </h1>
<form class="form-horizontal" action="{% url 'appadmin:createCat' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label class="control-label col-sm-2" for="Category">Add Category:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="Category" placeholder="Enter Category Name" name="Category" required>
            <br>
            <input type="submit" class="btn btn-primary" value="Add Category">
        </div>
    </div>
</form>
<div class="row" style="font-size:larger;font-weight: bold;overflow-wrap: break-word;">
    <div class="table-responsive">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">#</th>
                  </tr>
                </thead>
                <tbody>
                    {% for row in categories %}
                    <tr>
                        <th scope="row">{{row.id}}</th>
                        <td>{{row.categoryName}}</td>
                        <td><button type="submit"  onclick="location.href='/appadmin/delete_Cat/{{row.id}}'" >Delete</button></td>
                      </tr>
                    {% endfor %}
                </tbody>
              </table>
      </div>
</div>
<hr>
<h1>Create OptionInfo </h1>
<form class="form-horizontal" action="{% url 'appadmin:createOptionInfo' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label class="control-label col-sm-2" for="OptionInfo">Add OptionInfo:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="OptionInfo" placeholder="Enter OptionInfo Name" name="OptionInfo" required>
            <br>
            <input type="submit" class="btn btn-primary" value="Add OptionInfo">
        </div>
    </div>
</form>
<div class="row" style="font-size:larger;font-weight: bold;overflow-wrap: break-word;">
    <div class="table-responsive">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">#</th>
                  </tr>
                </thead>
                <tbody>
                    {% for row in optional_infos %}
                    <tr>
                        <th scope="row">{{row.id}}</th>
                        <td>{{row.optionName}}</td>
                        <td><button type="submit"  onclick="location.href='/appadmin/delete_OptionInfo/{{row.id}}'" >Delete</button></td>
                      </tr>
                    {% endfor %}
                </tbody>
              </table>
      </div>
</div>
<hr>
<h1>Select Five project</h1>
<h4>{{msg}}</h4>
<div class="row" style="font-size:larger;font-weight: bold;overflow-wrap: break-word;">
    <div class="table-responsive">
            <table class="table">
                <thead>
                  <tr>
                    <th scope="col">id</th>
                    <th scope="col">title</th>
                    <th scope="col">details</th>
                    <th scope="col">totalTarget</th>
                    <th scope="col">#</th>
                  </tr>
                </thead>
                <tbody>
                    {% for row in projects %}
                    <tr>
                        <th scope="row">{{row.id}}</th>
                        <td>{{row.title}}</td>
                        <td>{{row.details}}</td>
                        <td>{{row.isSelect}}</td>
                        {% if row.isReject == 0 %}
                        <td><button onclick="location.href='../../home/project/{{row.id}}'" >show</button>| <button type="submit"  onclick="location.href='/appadmin/select_five/{{row.id}}'" >select</button></td>
                        {% else %}
                        
                        <td> <p>this project is rejected</p><button onclick="location.href='/appadmin/reportPro/{{row.id}}'" >Accept</button>
                        {% endif %}
                      </tr>
                    {% endfor %}
                </tbody>
              </table>
        
      </div>
</div>
{% endblock %}